services:
  - type: web
    name: codementor-backend
    env: python
    plan: free
    buildCommand: "cd back-end && ./build.sh"
    startCommand: "gunicorn -w 4 -b 0.0.0.0:10000 back-end.app2:app"  # If app2.py is in back-end
    rootDir: "back-end"
    envVars:
      - key: COHERE_API_KEY
        sync: false  # Prevents storing sensitive keys in YAML (set this in Render Dashboard)

  - type: elasticsearch
    name: elasticsearch
    plan: free
    envVars:
      - key: ES_JAVA_OPTS
        value: "-Xms512m -Xmx512m"

  - type: web
    name: frontend
    env: static
    buildCommand: "cd front-end && npm install && npm run build"
    publishPath: "front-end/build"
